server:
  port: 4379
  keyphrase: secret
  signingKeys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEogIBAAKCAQEAwNjMD47XO24dvgfezQSKSCohdktGhj2Nr0N/3U+dGuJLCQJo
        jo2DqWkRziLzk2Osc7X1L5FgdAUHoZ/Y9gWQjgcKjNIeEVVebbtIIjb//dg4a1gu
        EhFefPCWMtBsdC8ssa4I0J5+/yvGxXjLxRuBWLbmz5kr03FfM3BB2jPcR2LPrJdg
        6epqUtpsg1dN1S5PJKIsz0t/GaEV498PSKRtqgz2TDEAd2mntQL6L7nSElYzjcWb
        NYxQRXkPDaWmeniIkPu0of4hryRBsswCLbB6+I/rvL7pCio1j4cRXJfzG0KtWQ8W
        d8gZw3ULZnm+jAaBq7avF8whq7JnqwZ/ps2MPQIDAQABAoIBADHrrR9V5advwOlB
        Vk6SH03BAjqCD/aOFpBJE99xTYT5EV16ryA/x9Zh6YcICy+bPLgTYS34HxTJfIk9
        PMeq9xmc/wEnHztzcudK9MhOnoPSpgA7qmlo76G+EdODmp+U2qgAGi4O6WcaqPDT
        bURP83LIngUdbHfmwDMrmxBmHl6n5VjMWlaGFaFu3zv8EMRgtlAsgLmJ9oIvYlCe
        Nbg8YLuLoAghIr548mk/qky921PPjPzwQA7mX4RlpKv8zJ7JKYMhOmy7PCf+/dpm
        e4FcoekvrWVALa9ko5GQwxaLCv2S9ZY3sdngX5AobaLZMu9E0VsbJmlOdO/OTDNL
        e4O/54ECgYEA06Xngrxw8BhowpeY5W+VnqvQ70Thf8gPVQErtSy7GFd//A5MUkLl
        gU83bnEdPgqJHUuqkJjFsSZfUIXF3q3O8imIqKO1sBc81c4ClAfU4A8x/O0YCoQ1
        SMNSFanyaJGdMu6a21db+9DecRQFvLTtJ7ZtevYy8/QS3b1kySxpNKECgYEA6UJI
        D/3BAE8rgDMRtS7Apuv4mKr7lXnUr0aOvSMjVtzf08+/6IiSUjc5/t/SdpR8a193
        iuOpYtseQU4pzWOUaXJomKWTHDYWzlWQSUke7p4x/1XtmLV0b2XJcVlfdKXlOwVB
        yM/mN75Jb6yDGbC2zhN1Rf2kIVMTYj976l5k1h0CgYBZ6tsfpPWKW6RuP7+6ghyb
        y705Whc/lXxGDfhGwZk/LzV1nZF5RWiB9mjDaBUXXZyBMLtnMTCUIYxPBnZZM5h/
        M3wWwW6YQFcdMqfPwkADbRE8tnIHTcHhhvHhuFD/chXKJKrv0v6GTmeivPHvCSLU
        Q2Hh4qUlFaXKRQODoHWV4QKBgFAL2OLz97l9cbYq0FbW1nHx5HuvoWpoRp5nnjA1
        0LjMT1tGndrUkzH3lcVrVbQvvIq0VjepbMVp4HYUtq+vDo0pH8/ScitqPGVOY5di
        qmTEkO/IsyKGkpBv47MsMl+7VnDsmuiov549hMH3931ncTRC5SnBowN0mOBMXN/O
        yNfZAoGAE+RFw83AV4OBe2sayPJPIsNGw1cIv0fZxqObt7qlnwxr40kfOoOvdaSC
        ndjULzRSozSOJp/ykWvcREB2wrPSispDUBMd2ppF+iVtryM65CNfrH2wg0tl3oGo
        B7z2TbYXZuy6OLmomHz2RMi2q79W6A+b5nIYicDBFCbswQ1sTx0=
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwNjMD47XO24dvgfezQSK
        SCohdktGhj2Nr0N/3U+dGuJLCQJojo2DqWkRziLzk2Osc7X1L5FgdAUHoZ/Y9gWQ
        jgcKjNIeEVVebbtIIjb//dg4a1guEhFefPCWMtBsdC8ssa4I0J5+/yvGxXjLxRuB
        WLbmz5kr03FfM3BB2jPcR2LPrJdg6epqUtpsg1dN1S5PJKIsz0t/GaEV498PSKRt
        qgz2TDEAd2mntQL6L7nSElYzjcWbNYxQRXkPDaWmeniIkPu0of4hryRBsswCLbB6
        +I/rvL7pCio1j4cRXJfzG0KtWQ8Wd8gZw3ULZnm+jAaBq7avF8whq7JnqwZ/ps2M
        PQIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
