server:
  port: 4379
  keyphrase: secret
  signingKeys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAyQ7J2CFKwfTExS1+RafMX4yEpsz55kKT0i3BkLn0O5Mog+RO
        vxnMzbuBVM54xsI85Biq5lqHvs5apxG63K55lVPsrjuzcMSse4iKufVA/v7Tm6ea
        iPiDowirzS/u4daf3r//dt1tRBRdk5jwIlPsDgRCUrPw9exHUobsv1FjigGBCWwQ
        Cd9XfYCqAIhfsfWQhE68RcWAzwgtcr+RuIEC+MPF9ozjCE4bi37l7/F5izwzWhLx
        CF2IvFkdRS4a+EDUZT18enPMXNLWx1qX9+ypREJR9a2ju3uQfNxaHDRkHYl06kXS
        1bUFqIj46ywSuarJj8pWElLFi2bpFip94ETJtwIDAQABAoIBAQCHtmi+b7Jze1G6
        uruKLvp/4GzF3oQsTfJTo7kNhMd70xg89sXErpiUoiVpZjkWCJRrbs8k0CTiwY1l
        Sk10mnzNNCoFbZzw2ICIniDt5sMpnD6fyaFBJWZNjRPSW7GGVYXyKG07Abm4g3qq
        n0gwE6+5wlw2UOmsRgHajeKOPVTQGIGylE4y138u8HRypt1y9TP0/vCU72/Y30wj
        M1o9Oz6kWa8cSj8wGSiBM22bX5Zi9kbWI6NJ0PHpo9WdYmPi+aCuytA667P/oDHt
        uyQeJtpPPPygNNcjAmbYnArmQzYVA4KOfzA5DrC6FKZXfkxaJaIjad6nK9NNrqsx
        xQpTZto5AoGBAMtkkDhLhiPVYoRWKcxi7KY+wwbM096+5gUXLfNT7zZYpf0z8YiJ
        DIeypcTvRF2FOaqMBbG5ZWLvb3hqyRLBlXUJ4HBvYRb8v5z+t+iQPo0KQj07jvK4
        brctwR+nqJLRLThsDwfNDz1kAF3N6gsaSHU2zn3UF0zxgpVVIe6VxNFtAoGBAP0P
        nJqEIIkEtMxTNCOBNFXnM2Dd97XvD1CpTYsnSEO2gSCOGWdF11p78CaYEyov2J1M
        0bswOjU8nu0nndMBcvft0vUPDJSc9Yj/LAAQCrMjw9DZnasF8kUcAH1JpXsg3hN/
        b8MWN/gfMBdU5vFwO0tgoNxl3t1WpxzlfAWI0bUzAoGBALfrIbamJJA2nrVILNfT
        BGd4DWcSxOuA+ALWaQjFd2RPWRnTZK+wLhJu6xNfwRRIKlMb9vI00YdbOBNNjLFX
        N8zzt240aTkeKC7Q7oBwHv/urOMt/h9hw0wFJcN4GilY2WlR3W2SchtzWBl64A5W
        H/tOKf8CUGeVZB2hM+PIrocpAoGAbuPebd8kGqaTS03SdRRzCImNfA8IMxMUlPX7
        YtTN184re0aJXzW9jorsyxysmTnqI9O7u9kASL/NrIJFqGbkKDxwyq3Th3PYLDYU
        49ojtigf8G7LpluutBX3KO+SsgfPCKA5KzWbRQD1o+OyZ24UrY0kMC/7nuYPyJvO
        4uX3bv0CgYBKmno5OvUNiciX2PyJBy/hHdo55fSyXmXyTFZTfZaTGGtl24rgGp4Z
        TQ2MsShokx0+aUSNpCQTJRLTVaAIfdem40J4j244BeCcYMjh/7oZe/n3pqvy8SYx
        EF1d0p8T8g3VWitlRhrJ3fGTi6oOPJluPjZuC1f1tTMfVLZIf79OXA==
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyQ7J2CFKwfTExS1+RafM
        X4yEpsz55kKT0i3BkLn0O5Mog+ROvxnMzbuBVM54xsI85Biq5lqHvs5apxG63K55
        lVPsrjuzcMSse4iKufVA/v7Tm6eaiPiDowirzS/u4daf3r//dt1tRBRdk5jwIlPs
        DgRCUrPw9exHUobsv1FjigGBCWwQCd9XfYCqAIhfsfWQhE68RcWAzwgtcr+RuIEC
        +MPF9ozjCE4bi37l7/F5izwzWhLxCF2IvFkdRS4a+EDUZT18enPMXNLWx1qX9+yp
        REJR9a2ju3uQfNxaHDRkHYl06kXS1bUFqIj46ywSuarJj8pWElLFi2bpFip94ETJ
        twIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
