server:
  port: 4379
  keyphrase: secret
  signingKeys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpQIBAAKCAQEAtBUVgzt88eKrampWdfGoAWfL3BSoFBl0ZlM14dMXRK+8d5nP
        D8LzQQNN77LjAQmBpmmYnCyyl5x6c/d8WaWOzIe1Vr5Cx9zy/MixnqN8qxkyPAF0
        HoLmI2guuC4gymC7FyquUuFW87bfqf7V1WuqbZfXor0grDOBwqrbuu4IWFwylQrh
        LT7acl033Rupd+n1sMIv6avp0wKfRWzyywL+izUUIQ863zyAI33e8zxMq8puII9b
        ijnlG3nm5uGnW1C3suBGWsSfJ98NyJKwhnw/dXn6aHPsC7WwghZ9PGIAw9++CM8q
        QbER5Ln4bMDYl929ZBoWvH0y/DwF6nSCj2qN5wIDAQABAoIBABPTSmYDM5MxoCt7
        /37GlvdopPHauFJWJxFo0cLFyYb/TeFg5oHWtY8PvRHJgOJJWKOodmujJBo62ORR
        d7gq2Ni9jAI7ugBk279mnN9ZIk133abrhgwh3xJA0vvl4ChHk/FN+pkXQ8pa9K6z
        ZnkzfDTKhavd5G3w0bVLuBsRP4vykzvz4OFLVmtj8/MyWx/rBK453Su9LtPXLJHK
        J2IKz+NdA3IfqyYuy2RaVms8uBi+DPsD8jJXN1C3gWm1Bq1zILr3y26y6I6KNkeO
        0XROj45AgDlkoLtoWZwRIKhy9RjXMDU6ODFbjmwg4Fgp35c8sHDkPMDX5A7wlhtD
        LyMixOkCgYEA2GVv9WF5UPMoos2gHldMpTw9t88wmPtCMLzPL6APhC7GQLkwvFj6
        y1pHV0v/HOWXK/t6Cx7tmxCe0ubAGCP8HDi6widxOjMH5h+q2KtFNIM2zSaFx8L9
        /zcMGzg461IV6WfXbHDHaR1VDUeprMuo3cuSHodJltGP/w/HFNIRT4MCgYEA1QpG
        RJCds41ihNcOUdCZLVrqdvtsN0uQTds6Md0P3aHo0YU1V/YPsTJ2DNS4uMm1Kp5B
        ch3TswjyNSIAH0EziDULkKwqA4IHs0CxTrchMOICgymPQmgdqoltNYB3X1MNGh9f
        pvsb+uUCwnIvM2wcweCI55l8PpJ35xFqUZdi9s0CgYEAkbxXF3ILCxqH7oT/Zg+z
        PcEBa84s04q7/CjcfB2W9ZWuzR4rlV1zogpt63vyFxsEoYlemyi8KueZnz3qdxed
        DcCi/mkj12dQ1YnUPNGz7PbFrIpaJLvM5dnD3H0T0F/bA/N8YLrfgYpQon315rrO
        Qnl8MfU4+UqvaL7Oe9Yx9FMCgYEAqkisIeH2K663MLc1GvBBf59MCg6tUQV1MsYo
        nfK029Ku5coz+TsVD+3lrhvaCtovlQEqDq0IqfJcp1ul/VWAez7rH5h9fJBS11S+
        ZMy8GvaMS4rMl6fhDo8KW9lzkR4xOtAZBL9yffjPW90pHVEtK0ruIzDrvpgUfv3M
        nasDz4ECgYEAt/qqURndE1VlX0dqsEA/NTn1/7m3BuQ5d1RkaVd0R97FtoQaRcxK
        WtnkqQ4bmBgz5vjmXVzhrrTKZxuS4kEPJdMbYY60A4yOno4wZdnBaPFgYFaCl68f
        RlFDHH+Xs75eBb1P5tSZsK8raS8/PhzKDE6NimJ2ROtK3V40v14VQVI=
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtBUVgzt88eKrampWdfGo
        AWfL3BSoFBl0ZlM14dMXRK+8d5nPD8LzQQNN77LjAQmBpmmYnCyyl5x6c/d8WaWO
        zIe1Vr5Cx9zy/MixnqN8qxkyPAF0HoLmI2guuC4gymC7FyquUuFW87bfqf7V1Wuq
        bZfXor0grDOBwqrbuu4IWFwylQrhLT7acl033Rupd+n1sMIv6avp0wKfRWzyywL+
        izUUIQ863zyAI33e8zxMq8puII9bijnlG3nm5uGnW1C3suBGWsSfJ98NyJKwhnw/
        dXn6aHPsC7WwghZ9PGIAw9++CM8qQbER5Ln4bMDYl929ZBoWvH0y/DwF6nSCj2qN
        5wIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
