server:
  port: 4379
  keyphrase: secret
  signingKeys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpQIBAAKCAQEA74PL5PJe7F9gdZvwF9V1W9TNVuUq4yXok2K/58vsuYIympPE
        znYlOmNPvGLyD2s7EZJ10gSCqEC2oAt5WoRoeAvtPNaP6dfflKKXh0cjdBG8hZ5T
        /Q+djJP7UEGwi4fbNHDxkLnP3jE0L9c/gYus6r1Mn8bdKnbl43jH2GXQ9YS5AxQ4
        /PdgP0WubDuMuWQdFlA3vlNoJMgTyNUUUE3IxLWrG9VsTE9RqdSPkyXaL4jf4iU5
        zO3ZSdKZWuq7ynp1QzBnbEnbYFMRV+68oa6fdQni/i8+XbrqjbPdQesoOhnFi91G
        /QbKHm3w7jaEkvfe8OFldZZzGJc90fGNOeDJQQIDAQABAoIBAQCkXFAV+1Cyajz6
        WBkpcd0IOH70q2yD1ebFBVXlziXTo4nwU4kRmTew2qfEAi5T8GTniRb7GQdESKxK
        JbWQLR63io+xWRgHA5G1IOJU/bdRlj5Ff0HpfcbCymYCTCHHjmIZmYvbofcIZcGH
        NvGoh14Q8/haCJCK7G6Ta7XQRQZhA/BHevfiLlwBs6Pc4gosJIhBRt9aGyHd/+3S
        LExYdwDvecGOzkP7DcBY9vvKIc1PAqb59wBGn644Ihxq9Nae6I1qRiJHZdx2w/7u
        R84iVMz4BxQAurYIll38KQ3Afggz/5TNrD0T3E+5rQFxtvTbUK+NYgIDq2Ar9J0B
        ahtAE9DBAoGBAPT+dHWhkvAzgZho73k8KjXkZH3CIcEkWslOKKbKSq6iCGmzAtvT
        kAJH8Pllyx4Bb0dy5hQ+QAn8nycBRJNSocGLLVC6wpMHp7vVKO7bjg3hHmokeS4T
        7YXh8ZYOCO7gytErN3sXNRTzNwJGp8oltq5aJZ5uzzHDH2u7sd6/5+F5AoGBAPpG
        VDUDrxXinNQiA249k5a6zBc+Bc90xHPYNum2vfA1eu9yzs2N0OiNcdPLsxgeF+wH
        OcKqxU2EoXhYA49P/O0O8Rp/o+pqAWLlxlSxMPjghVik/Cj2dYGqHooc00zvl5hg
        hyIp/mIcyrQq7Y2WQkiR8W5L8vHOBs5NJoAuDbwJAoGBAORWGALegU2gI6QCAVfU
        DF9IK6TN/5m8oWTHlLnHBo32dLLW5c4uQyTtGhnHluSzX5yO6QNq9VKZgVfgJaLN
        O/dgGO8J8XkJhHpa9BiSxrYG38r7jXm1lwXWDMzW7dp95mnGxqHRgmaxO87CPXX5
        ambbm/4qtq9hdXJ6cA/0elC5AoGAEGH+LSI6mdIltfUsCFFbkehUZ8kVlEjuey7S
        GWZu9IRrsbTwOKBp5m8r3lNdO9zsb/ThIQ8Qr0xZTYllYkI4KkRqH/PvBO8/e/vS
        icS3kfMQh4b1QrEva/d43E2av1SHtd/LuL7K+h0sX7LXrgcB+8Ih7bhnBNEZvPNr
        68QX/hECgYEAhcpQwTs+RO9EL3behT/xlaPZmF2saB+WCTCiMGDuAzFDJIhEfDk4
        uHJaytwYFK0/kp4WCGYR5B8L08FwHAYrw8nOYY2bGEo4gMFKRcZid0wIEqe+dkeH
        pwz1lqF6eLL38M7ln8qSaGpEl/RkIiNhHNrP4sabw0x6jeUxkwqvank=
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA74PL5PJe7F9gdZvwF9V1
        W9TNVuUq4yXok2K/58vsuYIympPEznYlOmNPvGLyD2s7EZJ10gSCqEC2oAt5WoRo
        eAvtPNaP6dfflKKXh0cjdBG8hZ5T/Q+djJP7UEGwi4fbNHDxkLnP3jE0L9c/gYus
        6r1Mn8bdKnbl43jH2GXQ9YS5AxQ4/PdgP0WubDuMuWQdFlA3vlNoJMgTyNUUUE3I
        xLWrG9VsTE9RqdSPkyXaL4jf4iU5zO3ZSdKZWuq7ynp1QzBnbEnbYFMRV+68oa6f
        dQni/i8+XbrqjbPdQesoOhnFi91G/QbKHm3w7jaEkvfe8OFldZZzGJc90fGNOeDJ
        QQIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
