server:
  port: 4379
  keyphrase: secret
  signingKeys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEA5NL1Wf3f7dnqff0+nZUHiNgBY/zWaPoCe1T2hUNswhx4syJj
        IFzQeOS4D1E3Qubsta9+7ePobf17rl1AD0takWscQG19LpxxvBfc6DFmDBl7KAqW
        4e8EkfwGO9WlbOIhf0/LBzApiGmIhB7Gti1UnCdId32ub6MrE6UktJpf1QGQa+um
        8KhtrVuN30KtdS3xyiakgumITJ8SWJuJm9ppQLOTHW3ObhaUvBztZcFu1aDo7O/C
        wTiPXKlMzpE+5AeS0Aalxnd5WjXi/p9WbzeilvOFLsvdPq7uph52eNyvzu+ZukiV
        cMoSnpVqy6mes9xLnlkAifJHAozYpVZjiDk8cQIDAQABAoIBABCxZx66i5SBej7Y
        s7GxRoxwHaHatxWPb5DpwNY19gAvLYr77jlVLAw1u0u6xApIaGpUtDDMmI81l8k/
        mkXDXIcRRk1Y73HwDcgIAaCawfQOA9MG+rzev/maZiYFTv0jfggYnRoYJF+EO2ZQ
        DHUL14lQwFOfQpN4VtMnEAdw357dTARdK+1DFLjvblX+++ZmWTK2o2dkAW4Tmthj
        /uSywffvZnv7zxRxNvKC5QxYjYPsZlKiROx/KDnzzmf6fSD4h30yH+Wc7CwvDmRj
        CP4Abz3ySd6gWT+rjbA3uUSSfh1wGFiZEaMH1vdN0RUH5ibyBOYXhzElCb9c9KF/
        ISs6MAECgYEA6q/KNj6y3vN172yJB+G+r+ORnYdA07Ay6nbzyCZMCQnN7HMKnW/k
        n6l3FzbEdLQZYbF6BNRVlPbZ9Ti6N+vZePp4FMApCfgBFhd27XCEit0LpZRSjCpH
        NjO2kabch5oqvToS0v0C9yWyePVTSsEy7DgWYWKn0zamDpla3d6ImQECgYEA+Zre
        cILkejeqpqvXQ0y91HNqPQI5IHJjN8jfUgxAUxy/SkeG9MtrH3EcMgA2Ap6CNs4y
        I0yRVh1qOrxl7xBLNHX/z0/Vbynq+/IO5vwo/IE5990t/DWdI7XZz+v7n1kdb9IB
        RcsjXbM1fabzXc79xLOA03wYICMkhvvg0ijys3ECgYBosYsPr+CzvQA7krt+nKIo
        bOik0ZWF2fCcz/voqcz5qzoF5TwzB5uB7mOGI5R4S2+XOUkppl+XWJfa4TeRgtE9
        Ot8ewqqMG+rAJC+VtMAsAngToZtBlAq4j1E+oKV4iLnQOHv1S5FrF5IKi8Zgbtd8
        sXiqcQxVGOfzU05J8+AUAQKBgQC9VmXfcNrBftJ7JaTfjyn8KyRubO5Kl5p9qWkF
        gveUVB0iykksDdYPfqyFnTVbHUPnMNhFgIJKkXuQXHLyOijh/ZRzfLqJXYG7Ze05
        +BNbHueLBoMoar7tZLd5iidPw7iZpvKCL8p+/D7aNrcq9KX4/LT/N4XRcvb1UcFD
        if44cQKBgBJ7T/2FZeAX4jmMffRzpO+mrazVbBLE1jVT6NKMQJC9FunUu9tQadBX
        qZZHkarS55V/NfFtm08Q3Vx2L2+zHZWxFAScH0JFmNa0xw/+ji1XEZQHg2AIbWbi
        P6w3Q14Z3eZnp7D/o8kUWS3r7H692V2YbOq5CRkph+hWdQ1bGHSF
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5NL1Wf3f7dnqff0+nZUH
        iNgBY/zWaPoCe1T2hUNswhx4syJjIFzQeOS4D1E3Qubsta9+7ePobf17rl1AD0ta
        kWscQG19LpxxvBfc6DFmDBl7KAqW4e8EkfwGO9WlbOIhf0/LBzApiGmIhB7Gti1U
        nCdId32ub6MrE6UktJpf1QGQa+um8KhtrVuN30KtdS3xyiakgumITJ8SWJuJm9pp
        QLOTHW3ObhaUvBztZcFu1aDo7O/CwTiPXKlMzpE+5AeS0Aalxnd5WjXi/p9Wbzei
        lvOFLsvdPq7uph52eNyvzu+ZukiVcMoSnpVqy6mes9xLnlkAifJHAozYpVZjiDk8
        cQIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
