server:
  port: 4379
  keyphrase: secret
  signingKeys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEA3Zci/neBLChphKo+eE2YEhQVRe2MqIj4ZG2gqYtvCOBTOv8T
        4GkcK9iSNojqfeB7UMGU8ZERHZvs6EGZjU3+AfzLmkezQNL8DziNOE79ojpehk0p
        c/fseh9KQ1MbaHRGOGHmQw/SVxAvbtFqhTTC3G7/aGHOhizcXMMo/gt5qfALVqJ2
        Kt7CQV6jdAm1GFaPzHfUjEj5tYG2qtMJLwnAEHQS1l5hD8Ci1O/sPZ8ZIF9EZoV1
        9JsGv9gUT22o1tXjNWlvmjojauubQk8Va/QNkHTHSLezLUa6MXuTYWohenhHTtdV
        X5O0VECU8GZp3jGgOCIxxMDRnaEjYq5K2Xr9TQIDAQABAoIBAHA8vFnd2Aywz3mF
        7axryQnnKDtKLkOzVPUxXf5ihLQfQ6kPSFcThlRjFvQOd4+Yo31s/+83hk7UCrQ9
        ffRHu8/v5oTXqmC8PTXMdCNAR1HjdLtb3BJEUoAs1yWws6I9us+WLtZq7iRxK0Vb
        RzP/XG/gvPd3Cu+FS3yk0V+UGmTLIuNk5/YXzqeHxpEzlmjX1KFAlsRTXDg/yM0F
        FX8C2furmy7Gm24zA+/l10I6gqmlT6XqmffHcLky6JXPBbZKQLMwlN07sGjBH3KW
        Hc1g9b6BzVbWgJ7bz8+vgfSnribDXMICHkZN69qx2tMvm5wCbUhlhP3quq9/jdrb
        80XLOhUCgYEA9Pk3iafO1VYJde5sZNMgiqSe37CoTQYfZagK5cn6SuWUILGqt+Lj
        zTkqp5wMzXGw7ZdLvfqzeKAOpNQpQ3K6YgFj/E3Ix00Z1MzL8MRpTi+VOW7g/Kw4
        v5GuiActnAl9ZQWgVxSokKQq2cZznQpYAPGr5czagwTT6eILg10xqAcCgYEA55B6
        /jISkJ6QabjWIYJXnCf0Kg5VRSOWqE33ji6iUz0EP1ZsNxnLjP4vaD6g022HuwR7
        jpNBLClOak0dJUlU5cOrrqbQxofwsuVa6hP1jNiDWb5inOPHxX4M/rwBGgxZjW+H
        bWdpsTLIUGIUrja9p/vD4GPmlHs3cHhwgumN0wsCgYEAwNBzbS6edn3snl0WBdnD
        cDyYK9qA7XcXOU0lnq32CgNfLsiIZYn44SvQrfH+hampp6gA3rw3jIb2X7f57nOb
        zc3oY8rZcDz4Su0SzCPb+sUq//SMs3PeirHgnIKB3KH/h4cBJ+lDr+z3KUew8fcV
        Q1D0isBNcPhYz2qywyeUEPsCgYEAs4PINYOv7LlgDvWh2vxm2sIGgQv3gs/iHbvD
        rE/uu0TUJB3lapnuuPDc452ZpA6HaK5C8vapUYj8J2B8tckxraWRVKYxt5bvPGCd
        qFWsyHGY8lurqyDSYAImJNyupfjo+8J4ZJIE18AclmRSz/PT94QwB6aqvHUBN4nG
        /1X8Ap0CgYA660Q6+hcgPXtRgcO8xTS1Czc319+rEBWDXr1ocpfJJuAlYBDc1l+U
        tE5uGhk2kv4BzrLh5wdTXZlANLrBjwVee3qsjQNOSeu57GwQ74j340aofEtENW7z
        xVuY++X6aj5G7rclvffmaDNWxhFrpG6Xfl0CcmawSvtvquXkVJFkUg==
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Zci/neBLChphKo+eE2Y
        EhQVRe2MqIj4ZG2gqYtvCOBTOv8T4GkcK9iSNojqfeB7UMGU8ZERHZvs6EGZjU3+
        AfzLmkezQNL8DziNOE79ojpehk0pc/fseh9KQ1MbaHRGOGHmQw/SVxAvbtFqhTTC
        3G7/aGHOhizcXMMo/gt5qfALVqJ2Kt7CQV6jdAm1GFaPzHfUjEj5tYG2qtMJLwnA
        EHQS1l5hD8Ci1O/sPZ8ZIF9EZoV19JsGv9gUT22o1tXjNWlvmjojauubQk8Va/QN
        kHTHSLezLUa6MXuTYWohenhHTtdVX5O0VECU8GZp3jGgOCIxxMDRnaEjYq5K2Xr9
        TQIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
