server:
  port: 4379
  keyphrase: secret
  signingKeys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAw6nMJHWD5vhIhJiEaozgBofiPvUcmyJNMZ87w5Kpe6N5rQxw
        oXrS4phny/5ir0xP63SmHdt0CfQekY09oh4skR+yG+6aGvKiM8wLTNxiHcQWDJNj
        RzvYxaQhFCdSRYmUJgeU/zE0F5EgqeCdkydURn/SjVcVjpt6i1uiRnryM6r/Z4J8
        sYih2zT1atQ13qj3CCwCMn/hHg1jG9M+5iVEBwIiVAFWRX2BMDETvJ6hjbQfNAvT
        +um/u+6mcd3qQQcpRrv3RNwF/4f0eFC25CmrXrfspu5rRku+m3/2aKk+zcJUvlHq
        lo0HqlU+cLv51YsKN95EZ5g5YD5S4Ga9rDc3VwIDAQABAoIBACnbdTSHf0Q18S2M
        gydYI8TB5QCa5xe46tKmwd5AzckJW8pNUvr4j4yyFeJp9SqTJLW2KqNQgy5t7uws
        TvcThW02Xp/jF0yUg2aZTAGRU9wSSrU+AosGnoUJa5ooH02I9Qx9qr49BGvWPCqb
        RppoW3sJdT2PV6k+UaTmYXy6aH3swumSNG3yCA/HcPoQok8stD2Tle9+MdZvmuG/
        2Wfk5oURFxqZlEyXAqfBXjmQBUJDsUCSVfDmmTaTw2oLUfhhD2ipw8HvDSn3rtOF
        r5PQumfGrtZMYm85AWCCwBKOnl75+yZG3BO4gByDHnm9Hqmowfg6yoj3vYybPFNx
        76aGkKECgYEA7ryqm+BZD8BLwEg34NrlrsH0OTpq2vOO8MoyuHBJlFSeKWGJJYlK
        561wvnCg+sXOehREKdzKCQn8pHKFO3UuCyC98zl6R8h4T/ew6b/G/iT9Ls5gBzV/
        If6tIRjG4FpJa4dZYaSPA6fLBOASoxA5eJvt9sJVsTZTZ1JcucFVoasCgYEA0c/H
        xe+rxciIWD09hXFWr0o8+sxUZbBY4XVwaITvXNXSQesUg01WebBA/auOp4rkfDe+
        fSPPn/VqRBB15d9wrTMLcnv0tocF10daSPzwZ2Q3zxCp/G5fMGo0nwVDRixTjKuT
        oDKMOYdWiDY/R5nfDRlnq7k7G+oRUkVlxKhgLQUCgYEAkL4GWldc5/XYd43Rgxx0
        IM4q+f93BaShR0/wDG7XzXy4H7Ko6f8hUPGQ54V1tFT1aIKdCRx5yZ0qdbGRIYlc
        Dxcc0zhH8PmUKDeuJSpGxZM7hYNOKVC/8aZs5SIWgbN7zBvVjyOsKbUzm5MW+ZI+
        pec0EWWlernLO1tuKJkVB90CgYEA0HrXdj5V//zoRk3r8MoTKbDp8QfSIQ1e9AD/
        Bkx5kFTDTU7rHiFd+SMDIU00PhUMPsYhWTWZXMe+pQ16KUWiL+gVyteS7UAztJup
        AfecZhA2SGG1lyiRG4mc6hqPo43uI0xmL3uqzItHl6fXry0db2W8Fu3C51Tpi0d7
        /TKWBoUCgYBVcaNveZvYE4eXOBBe8IQ6zMBK6SKZIs/rp0QnYtrfRXxlCeiI5Z3f
        +5VpiP+RjAzm+qq5CEBA6KNULD+PKjit88Za1CGKTK6f5iVyDG5Of1ZsniV/D7Et
        2cOWcDRlJvlfsKry5/N9j3bmK+Y5qzHhh7McONb/32cww5AvepZECg==
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw6nMJHWD5vhIhJiEaozg
        BofiPvUcmyJNMZ87w5Kpe6N5rQxwoXrS4phny/5ir0xP63SmHdt0CfQekY09oh4s
        kR+yG+6aGvKiM8wLTNxiHcQWDJNjRzvYxaQhFCdSRYmUJgeU/zE0F5EgqeCdkydU
        Rn/SjVcVjpt6i1uiRnryM6r/Z4J8sYih2zT1atQ13qj3CCwCMn/hHg1jG9M+5iVE
        BwIiVAFWRX2BMDETvJ6hjbQfNAvT+um/u+6mcd3qQQcpRrv3RNwF/4f0eFC25Cmr
        Xrfspu5rRku+m3/2aKk+zcJUvlHqlo0HqlU+cLv51YsKN95EZ5g5YD5S4Ga9rDc3
        VwIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
