server:
  port: 4379
  keyphrase: secret
  signingKeys:
  - id: cc7430aa-e85b-4751-94b1-836edd2ecd17
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAveVXBevbJs6rhp+eKXP3Ns+7V3/QjqB8VU0hfiimcHRlpaFk
        xfmyKJrbk5ttQKEOdAL6OQiHCC3bA+F6T5nS1/G0vbTxcWvmvTAZiVPoMOykj0k+
        nXy4/MijePgpdydrR8bC9y46qDZ0UEN+uCBLKmh5BSkMMwHEpu043zZGhFqXbxlV
        KIeZeUAjvMcyDki4RWq6AZoX60dRlei+yO7yu4dzRtGYRBQzasfyRZ+6i7A/HvOv
        nfZ5VsVq/2JIjVBO+oG/Bljpw5dkO/3AAmkcFFETmdlE3kX1XZv3gtC8rc71h3W0
        tEi75jwAMruVa07FXc3euAwD/nZPJD5AEl+TJQIDAQABAoIBAFlwMguM6ZwejPUM
        Kr8VamM7dd4hSgZTGhxHBrZXyQSAHfvjxwXjtACh5zdfZhahhKApYtcH6Cl3B4eN
        ZEEnjwG8Ssdq+KjWDEgg5nYiueKJInyGH+KnAq20hiIMp+MCAuo8eElZUbE2bJP9
        JirsstpXeGBw09kWRRvl8PpYot/kx1FWlchr2ChOxyM1gO0DKyL0Pjy4aanORB1o
        Z5jbGjuW7hkDg9rLXp9JoDyoxAm/6CEkvDgbtZcYyIkOBnm/x0z9cde90gSo3yjQ
        kGMAcIX8mDiVHhQQePBmWbsBfVYvBQZJY0/xdUNeoG85hZvZAu5pqSVTf0PnRp0g
        g7E/ZuECgYEA1cPhjeY2Fl0wk6XmQYjcvUOki9vwcqRQjxetn5CdVtrECF9vMIQw
        upqnVHCkUqvLlVAWMs73J0vL5zSixqaJmm6bLcApEaiDT5A7/m4+T96EvfcLuxZ/
        fWV+4h6EpxJaRC+b2mWoB+g7aSO3q80gDp39DQHNWvEMISrXtt4zP3kCgYEA42op
        z5PZGaV2UUPdy41XaTheOeIH6HQ00l6td2d4fSCwfnxRDlmLCIc1JbI07tlzExQz
        gZhmns97MoP9hd4h0aA9ITE5LS+yhinuLv3+3KUF9yDdDvVPpUDpr87pA5I/Nq12
        f4npor4qwbBxdNk8hC3s8DUulzWeLSy4dkvXqg0CgYEAwXAdZtQA8+HmeGWy5HDe
        F6LjfvBLOOK6R5KMug0aZCNZK554trWYhvQ2IXJBMNJnSrmLLPUesH+lh5aZChxf
        /tDCOfde8qzEDrado5LNbmcVRfYNtoIYYjf7RtGJBsrTxkoyxcIh+O3M/UqmBaB8
        tt1+xUtxMi9Y45aqV7/hLjkCgYAlRmNwCLXPBFXuYAdcs+Ad+QVIy4msSk/WI3qf
        VbBkIhWLxeirR3YIgdDuStVuSOoZuHfwyAAaC7wPvZ6ycIRujas3Y5ARnf3PC9Rk
        k3FQzSO7LAHPz9msJoWnMWz0DuaZmbkQkpRe/niXosoV8v1+VOC/RphKZJl2ohvi
        F/BTiQKBgAuK7EpZID5N8T3UKx/uB85Hp+qlRwTOj18JNnDuBgh1k+gZ8uXJdrIC
        NoLGXz//a6TY0JCCFkt4ZLBqHGyOHgl9a7MHPX278flIQdkeE2wZrc9fu9hIWkdQ
        omDTTEYqUzhFtUyv00XTNVmjRPzdt1IjLGhIoBlann6EVwOcJe7L
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAveVXBevbJs6rhp+eKXP3
        Ns+7V3/QjqB8VU0hfiimcHRlpaFkxfmyKJrbk5ttQKEOdAL6OQiHCC3bA+F6T5nS
        1/G0vbTxcWvmvTAZiVPoMOykj0k+nXy4/MijePgpdydrR8bC9y46qDZ0UEN+uCBL
        Kmh5BSkMMwHEpu043zZGhFqXbxlVKIeZeUAjvMcyDki4RWq6AZoX60dRlei+yO7y
        u4dzRtGYRBQzasfyRZ+6i7A/HvOvnfZ5VsVq/2JIjVBO+oG/Bljpw5dkO/3AAmkc
        FFETmdlE3kX1XZv3gtC8rc71h3W0tEi75jwAMruVa07FXc3euAwD/nZPJD5AEl+T
        JQIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
