server:
  port: 4379
  keyphrase: secret
  signingKeys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAuLgtHV4n/EL6byfURDLyzTM2EJgygYG6K2GRQHUJAfVA64Dg
        +P4yXb0G+vrUIqCzKpAlTFF4j5pfVgpx7ids+NMOUks+w00dAqxHNwvrggXYd5cW
        iMI2tqfXpJPSnruyQC5JCcskkw1w191w9TRvwMF6MNPMMtQkA80fGO/+T1CE5e/C
        wIlD1ZjOXN50vBNajn2+N+j/KtUrnjyQwVurnyuaBfndYD2uReyKpINQdmxo4CPx
        McV+Cz8O5tl3BCcLMOC+mCapTvKdbGV3T9Ejc1+szohnAdBj3FBxdYlo/q5uJpHl
        6ogDHOF0TX8EJjUDZKGLAmV2hkTt6hRDtTfC9QIDAQABAoIBAQCASsJirDtfM/GV
        c/c0KqKBrDi3i81ALyZq7MeiGebYqkqdhhQ6OuomOpv3gnAFYNEvFZAiEk+GhTQD
        oRuByXYg1w0SUNpVcGBes+J+M9QsqPywCoqHD0RK1gWqc1SMFFZ3xu3JVIKhc2tV
        MaI7W2DmYjoIYYFoJ/iffz5C5qQc1uJ2kMQaeMrRECKqE2h/ByZFTYVgbir2w7io
        MTWtekQG8Jni1V6NApLYOsiXS6dpNjhDOBkql2X2x8l6EY3Iq08nf07cH9il/yyY
        mM9vSKGdwWManfUhAWGsOSkGW2VFliDruqnmZU/fEnVQYMYRjhjr+HPalOdflwp+
        77qF9Nq9AoGBAMHYoP5XuhT3QG+H1yfKATrpd/sg6V86poBKlOTFNUAKKWYsGywo
        WiV9zSpvkl1fQdIFfyD7z7DzJoKtBQHnG9cU3gD0qMXk7RLqQC+S91jDRRGmnWUL
        TfzWE2Bhj9cXCQM+A3FIm0LNXSpAZtUbtrG7iZlh4eA1KsCnDWaBUdfbAoGBAPPy
        Zl5YKuyxtKNeS0oHno9c1J0E+DzlKRZstjvZmElSzrDZGoKGAl4Ms488jKox7zG9
        Co3irxtGsFKq/AZqTzrpBin4j35brNTpxUMxWI7K+JddekPSx/iLG3dGFbRjK3gj
        M/3DYHU2kj2sTN0iA2GGtdLj4gZLFPrAF62VcvFvAoGAehq8/rm/62j728VTkCq8
        r6FVBIlst6G4M+PG+nwG2PoNreBmlWAtuKQP0oVJSyuvyF3SALLd1vay8WmPV+1+
        KfNpDG0QyuczNtD78Xu/9te58C5lwrpmO7eVqQaLls9ZzAMKJBe6RVAbOXwryl2U
        rUwWltmDcLnM3mHcHQ+kwDUCgYBwSjkS3nTLxTUIKkRvzDgRd8KqkHoP1dBm8R2l
        SREPV12rDBRm1nbKggA5Q77gLOIUvBbanujJnm1VcD1YWqEj1dWvhinPGTXiP8U8
        m79O42Ewk6fPBnxkDOxUp98fzLJat6GcAs4oxjjkyKYM+DYkM1UIwTrueKssjTWZ
        An0JYwKBgHZ/o1hT7eA/ZCVfuDvB/Hkdma68QESHdnDW3Fl7O1JxH9zZE+thWSrv
        cSOts1Hj61UYGjRlzKJcUxNbNcR2LK63+y+9vdvckWrCyidSF0onyugUNvvI09ar
        bPDJaUs1QPXUkILJyLslbxoZpwM3OD7UIOyiFbZxEgWU5zH/vydY
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuLgtHV4n/EL6byfURDLy
        zTM2EJgygYG6K2GRQHUJAfVA64Dg+P4yXb0G+vrUIqCzKpAlTFF4j5pfVgpx7ids
        +NMOUks+w00dAqxHNwvrggXYd5cWiMI2tqfXpJPSnruyQC5JCcskkw1w191w9TRv
        wMF6MNPMMtQkA80fGO/+T1CE5e/CwIlD1ZjOXN50vBNajn2+N+j/KtUrnjyQwVur
        nyuaBfndYD2uReyKpINQdmxo4CPxMcV+Cz8O5tl3BCcLMOC+mCapTvKdbGV3T9Ej
        c1+szohnAdBj3FBxdYlo/q5uJpHl6ogDHOF0TX8EJjUDZKGLAmV2hkTt6hRDtTfC
        9QIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
