server:
  port: 4379
  keyphrase: secret
  keys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEArPX34pFgpChwpOxXmbE96Nl44dEhzqxTT+BkwDLE5WI4wuNX
        loPrb5acNGvv/mJfE2Hxr0FDKWd5F46rHC4kyFKTORHXbhpccBcCUCTgxIcoRLba
        cU5xnTN05/8DFH5RJGOPoQCuDIxtqSgl0IsnjtGVG9ufMbvFfMpHSbjxQVG+C7a8
        E7YNd+F/55mNwcrggkTdsp3j8wMIRWDmNdqy3UAjdRBnuQhtjW5Dvz+ea4X/09P+
        P4WW5UslbIjlt9FkNTVub6DWoclOnNxYzeAc4R7YV55IIUV4qjlLfWtwpjxRfjpE
        vGKGM19muJ1eUOf+3z2HhtlilPv8j14EjvzBbwIDAQABAoIBAAelQ9TnGj+HbhtM
        Oz8W/6aYXmiVBwqMwY4JXErGs790DRBIXmnP4Qtou/TxRIWZMZy4uqdFmkNtSIQL
        EXNIcuXMCKgAKua6EZX+3mJOjwUA+H25G4Tgs9MAIE3VDvzL7KhQIlw6nHb/iiVt
        GebTD+eXSiEWHz5ij4NJqccPftKlSMc1tVr+I7TAed712euJr5PTa0aD11BUeJfH
        D9ZWqOg5TB8Q3A+vx5cgl9wQOXxOgNmbTsgyq7bI/RhAMHLJA9VZ4qnadhwgKgpv
        hYjQIcC1IX0XMN0U6s+Q9QDuddQc9rbYzRK2EvtMqzW94Bfu6yUPWuaGB5aLIkuY
        jKX6VBECgYEA1ftRnhESc74PKlDBgVL58o7xD/m2GkW590DBh5aD7kj+OGxeiCY5
        C5OuqOGFPHyl1GKPk74qM5Xsl61c0LDSr4CsPnUmfAN+sDIc3NfoIeQx+IN/LLx+
        a63AnFz7KF4RzZ4YCuKmXn9i23v3H3kSDtn/Dym95mQSu5J0jNDnJdkCgYEAzuyQ
        MMVEuHy+ZYuOttvla6bj1VPkLgwIve5LzubfXKtkQzFBz/j6CiWP+eQr4tBj0rZE
        pZQNA5Fn7mY/5yq+JKJbaXCzy8PSxzCNeJLC/5jnYNNEIw66KJo6PxY8QVatOcCK
        gaXZsmgcImWk7z2425wK9J5qvZ7dVqlrK1i6rIcCgYAJfqlUdjV3ZUuO+R5c+q2U
        kbsolk/6QnXJ/tmXhpo8DIkbP9PB/tAxL1Bktf0PfghtsCHm0F1XBKQG5u5jZDU1
        DGSYMOKQRids8gxN0FbAijudZ1hRR9vkM0WEqquKUwI/OXCfqwbu0oA0dP+2Kc0f
        U5T5u0Rt4KrkH8+EIBDhoQKBgQC0zm5bvzOCBLYVYrFsRI6d1zEDKY+bULaex0cE
        XiXUAorUT4kTIZnSHepFT0Otp6th5hPrnocUlAx9emjiJC4LMravVmQ0a0KU/G7R
        aWPsFP4wU8oY2/h8G+9DSrmR2hv4963PBU1In8HdqHVK+uK5Ogs0nevlDpiW7eiP
        8rMCpwKBgELBH3i6s7cmnT1OXR04ro+q7QtGgAqLkhTgI0eCbct10I04LmFU2H1r
        1InjzUe6RfdQ6Pv1IgYUFcs3jiIU7ZeAO73Ct0vRSzmLe7FVu80Hnmv/glyljovU
        20wupgIYjekOVwhi51q6JxaUNKvBzQSgIXMbv8wp7oMz1fz+ft2U
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArPX34pFgpChwpOxXmbE9
        6Nl44dEhzqxTT+BkwDLE5WI4wuNXloPrb5acNGvv/mJfE2Hxr0FDKWd5F46rHC4k
        yFKTORHXbhpccBcCUCTgxIcoRLbacU5xnTN05/8DFH5RJGOPoQCuDIxtqSgl0Isn
        jtGVG9ufMbvFfMpHSbjxQVG+C7a8E7YNd+F/55mNwcrggkTdsp3j8wMIRWDmNdqy
        3UAjdRBnuQhtjW5Dvz+ea4X/09P+P4WW5UslbIjlt9FkNTVub6DWoclOnNxYzeAc
        4R7YV55IIUV4qjlLfWtwpjxRfjpEvGKGM19muJ1eUOf+3z2HhtlilPv8j14EjvzB
        bwIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
