server:
  port: 4379
  keyphrase: secret
  keys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpQIBAAKCAQEAxQcUHxErFRfOOqyT0lPgeAo1XbjPudYvqe9eyHZ+4LTVNA5/
        YhQs4U4KlzlkS9dVRUV9wmaurUKn96BAYqrf5jBO51Saewf2Y8cJUDH/k+5iwYL4
        +vU8ALLTJJ/91C4A1FQOUrMYZgzTvdQ1mWvv2QtYWuXwpGbZ1WkptI9cKGc8mQ5d
        a0CZ9Y6r80llfMm1PEen9GfmwnesCTiIlhX+8QYuse5AwIMmWfYhF/9o46K93dVW
        eIPeqB93KCKPhzewaEkkE9j1aHTyjovtAK6bGelQCExpRon4aMksMippbQEv3WlX
        zOiBMXL4Z1Dr+2tEQb5DIgTj+DrsOUqHA0s85QIDAQABAoIBAQCghwfp1/8WDHNG
        ct1tfFFi/E5GshDtBImJFzJOed0eD7e11ioLKwz19LPESkphUGx1KA0ymp6vI6Pe
        qX5L5ZTO44UmDVRf8TjaSoxX/qSRTqS/rYpWTgA5QXmuWXxhp6mdVW7mCm1SmBjc
        jU2uVrbwS8INLVNHX1UT/76vEi6v6x8CQSswAogr9g82HkcPS0TaNddappovMING
        lQUu7UILEWUqLE9EOyb33PnrnaMOkGyF2Ot7m2hIvZSeNRploqXB1cs0YgULoIju
        rKPol0Ry7fwJ/DXyGScHlugO7XiH54yYQD6Onhgdf9yfHLyoXbfz6bIzujkZFTz6
        eNn+/LSBAoGBAOM4e04yoUjI1W1UqOoZP4jpHLSSQXgxMtRsnZo7HpJ6dAt+rvCn
        NJ15d1yMtvYyswZ69L1MOtmWNxZ13Q+tCfnL6vr5yr/CuyzMMoqaT+0DJf/eYq+4
        H+aoMME4hIumxmK8mmIy+vNjW5AKz8k6/lxo2DbMA4Cyf/JaMTIFz1c5AoGBAN37
        mq9nqAq+O0WUiEsmZAwyDfdP+syWAxIlTP62xsj0W8mWARM6G5po7IfwwMsAnwqH
        YmKSfL3wpSKP+VLZSpj1y2PybdJRwleWotwrv49CnDIwgkNCNRiEtsvyZDl0iIZw
        47cRqz6L6PzvIPslGIEMWAdmiMvBKh5n6+EQK0cNAoGBAJqMMFJf3ZPEBmb2zm1r
        /usAo6WuVRmLXSdfOVNOIt0+rO+kmxjUodT6aVVp4IhUs7AUsaKP1vdoVM/SGyou
        aDqfmJRckqsbqHQv77CWhQaQvafrevRKKGiavY6vAnh6VzWRUvC3/DjPu9edgvc8
        SQZRyb57xWYkAyK0dgGwMfcBAoGBAMkz5s8Z+zxRlNPKf4buMzzCmdoSSlbpmbr2
        yEUPUjqPEiszpaHRx3c7pzjIRVc7JuyaLdj+wcY/us4LBYfMoErobwQWluhNZwOQ
        6+j4Vlb5ny32vftMpWel0zIkcCeLsrt400352+eDVRj9fj1lMEK394otq8xTN2P7
        +dczmqZ5AoGAZNCt/Ea/nJSFZKrXj2kvr6eEdP4ptbzj0dqkXLBnkmfBBSMAsOmR
        p4juk0DRfKEo9yJFsh65Rh4FqYuAVSL0vdPL1iXlZLXRhdBWKnMyFbiCZbOz1YAn
        8lGL1Fd8wHkBtYuq2dYEuSnIDPDcLPrKcJWUjdB7qappNUIB7FoYFkU=
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxQcUHxErFRfOOqyT0lPg
        eAo1XbjPudYvqe9eyHZ+4LTVNA5/YhQs4U4KlzlkS9dVRUV9wmaurUKn96BAYqrf
        5jBO51Saewf2Y8cJUDH/k+5iwYL4+vU8ALLTJJ/91C4A1FQOUrMYZgzTvdQ1mWvv
        2QtYWuXwpGbZ1WkptI9cKGc8mQ5da0CZ9Y6r80llfMm1PEen9GfmwnesCTiIlhX+
        8QYuse5AwIMmWfYhF/9o46K93dVWeIPeqB93KCKPhzewaEkkE9j1aHTyjovtAK6b
        GelQCExpRon4aMksMippbQEv3WlXzOiBMXL4Z1Dr+2tEQb5DIgTj+DrsOUqHA0s8
        5QIDAQAB
        -----END RSA PUBLIC KEY-----
  - id: sample2
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAp3nmnI6TTHfSgv/0XSQJjXAUtGzVUKP/H1ivmXzWD44YLnmk
        sSPLEq0SL4stE89PgVVqkaiycSwJW4wEWJ8OIBKRY8jIn70UDy+45FA/dIVZpTrG
        Wfi11qsGBFF+7NK94UbpSlk/DEqEBsTokCDGWLK2sohKiyXJKpg+r0zstuLBLImr
        PKHoOhw2ZzkcE/NBODrrIsthqcVfdLzVmY5Z/y9YZb7Am5kjIQSUSxk4s7HOa5wY
        952hXikNbTi9W2oodamGyqUR+LZQqsySbp4ZHNe/k+/oAtgVSGyAKyFxd5YVJ/+3
        BLYWny7mqxBamU8HiIHBq2VQ8hlYGSUH84F7jQIDAQABAoIBAEF3IzA7g1S22fEf
        QFRQS/Ofxlgo2tGk6YtFTY7//2UhNE6mejxMM4tfX+Z5zusZdIin7Pp3KRmYDyhb
        +S7zLcBXwcFxsQrQDFFLZEjLHaLcpYgzC2oMEHiTbcyuVqEYV+UBpRvM+xpA3o8O
        1aHRTfdKFKSBJjJyWMpvrME1nqp2IvUewwq/VdrwD2MUUuu5G20A1w60e/ZJCegk
        GwLwpTwgBZEWagqDRGDmMlVRsgoRz2a1XJOudzI10ND8xIpvWZKrQFALa6i9p8o2
        X2L6k3g2UhqH8fMhHuaQDf4blqU1az6Y9oSEqv+aO3jx3AHYTqcvsb8bauqwbCSt
        MYZ3FkECgYEAx8ambx/AG419lnBsxTrNOS0rB9zPCE8uZY88DLRLGyBqjrJQd6gB
        PeTyxd1N2CIRCmN+WW45E8OjL9q8C4fAbsoAgW4+SrV27Pr/iYTsXMXGA3enBxgS
        QFupZLlyQdVSG0cLlXifORTH0dbCYRiOFwGBibdO6RjMas2W+MRL5kkCgYEA1pwh
        3oDobcc94764dAb53viSiQqXkr7t34XzO5WfQlcNMzcyxoiyBzWHRX1xcmYPZKxu
        27n33FyJUBVrT8OD86ZLt3uVDH4NmV7L1vRY36raOw1+nbGP8wbfzS1vvj7f8R/t
        Ynd98BCdsTUkp3atd+CTC8bJqM1V5G4tXYNDmyUCgYEAtXohiuTe0Kixo02xoWEP
        OJdtdZECiVvUm/GH7UqCx7uk0MfvDSOTLTSjzVaB9orLzBIhnv/f3bJktX4QQLEq
        //mEiA8rixZZWGGSbMxRIt2OSWwSUQFu4wPhV1yXDHLKSXk6bqfKjEHyWw6qOSXj
        Pcbic8YPavRaDdOBB67Z+/ECgYB09CNVAYUpBjKJIY+d04tqYqZgvn/5vckeTf5O
        02w2GACej49BOI9kdFxil0ky4cGzyHCll8Qmt9sw5GtVzaPkLRUISfXhF/TLRyjo
        3MJuKcrB8cm1oGVlOLLQOtmxoMwjuJWCWsIsCLIXN3HhPUCtmpooCc4uCrCrSwu3
        8WfvbQKBgADTwnNHJPdu1W85zKkHMgC+ltJDHT//k6ZaKpXmJGvcdkF4kUy9xpne
        jILfvoDJB0BgVuS69Onb7zreELyKr+YQcfSXzZS9yI3fpfbObcrbqSa2hrhmwMNL
        vQcB7MQ2P4LFknqkuxZCbX0qGbPJQEotHAHSiKcnx9IU/lmTGgV2
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp3nmnI6TTHfSgv/0XSQJ
        jXAUtGzVUKP/H1ivmXzWD44YLnmksSPLEq0SL4stE89PgVVqkaiycSwJW4wEWJ8O
        IBKRY8jIn70UDy+45FA/dIVZpTrGWfi11qsGBFF+7NK94UbpSlk/DEqEBsTokCDG
        WLK2sohKiyXJKpg+r0zstuLBLImrPKHoOhw2ZzkcE/NBODrrIsthqcVfdLzVmY5Z
        /y9YZb7Am5kjIQSUSxk4s7HOa5wY952hXikNbTi9W2oodamGyqUR+LZQqsySbp4Z
        HNe/k+/oAtgVSGyAKyFxd5YVJ/+3BLYWny7mqxBamU8HiIHBq2VQ8hlYGSUH84F7
        jQIDAQAB
        -----END RSA PUBLIC KEY-----
  - id: sample3
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAulqTZutBMcqi9r0NEPaYgRJ1TRqvqjlPc4+l+q1GKantO8Zc
        nSvVqnO5srUpd9eXYOFbH+KwMT3E1ZZPu2SezJx2eKn1Gze8IWHF2K3/CwMppTL7
        JWeu3Ah6mg56Ls541M6OLPXQ5NAzl6deWNh//Kpd5li/aqtJs7FqSzzWEPNW/AB2
        35aehiNKlD+qIKmqls8QFljP8uwRoLXrSntPHUQBxNuRPLYCfPB6/jMWjHK+RyLv
        xTGnD9/zfeCwfhjKSW4jubZeLm3+NFts+aOx6FD+p7IvA6fi767RzisfkB4SYwGY
        fEwra0mukbSW2JQWUpFEoYMQ5+VCZQKqh4w70QIDAQABAoIBAEHFGeTm/rluBRoE
        GwpzndtgAlpWIs13MJ1eg3v3j53AxWOlXKZ0BBMGiPGTkrEjO+ALaTfVr82ROVkQ
        lc9TceBREFcB1OnoP9OgSE1zC2J9mUMevRi0gThTHcIlfeXrJSYmSHOBxlobSToq
        7dd5gaJRFpbnl5c0IOz0nskzDXIpdUD23xnRWgHetaJqDK2X0Bk/qIJVaPo8zIrG
        qdjigCae0SVGKI3Frvts3x4x2x5YsBpu7auAAb4MjONR6w/Hf20aoWBqwC0GG8rm
        znJ6nCj7Un+26+UwFCFwFSQPV6kHkrqxivzY9yfKBxNn2mgCQi/dVJFZTwbiefdr
        2W6lZmECgYEAyOismeEx3lxvdjq+IEtQes8c/J6L/I4WnvmwFyOiI4V/5ORuOZ3d
        Qn7UpTkpW3MHt2JNuCH6rt59iIYaguJK5lAToqMEJWop+yBn/OGRTUxuPtBQ8TDI
        6rLkQnm79fafMiy4yheHzJrdi2Pji2wQpCc7YW7jehNqu/y39EpcRw0CgYEA7XQr
        jabMIGVIsqswwMGTYow4MwLyQ9NFgzb1TvzxBWsbh4xApu8FDrHw87rM7nlg8z8+
        +xduVuOYnjECHhhEdVriDuxIXKxgx4swii2IJezMMuQ5mcZA/o0vmmsS4bLT0Doi
        DM/nlpwrP3mIYAGRelYEwVKREGASekGIv7rSFtUCgYEAi67hmhcs8dm4kS3kVFWo
        vcnT8HtW/p/XcG5PFLdsml/N/NkpHZv5YqsFs14bt/4xBjotqPDO9tev1cTPF+K3
        iotwK2pFjrHSQExWoEZAHMsf90IklJyDhFIeS22R1j/CjUL0s2VKwGGH2Mr5QE1B
        ALBaI7LSK2Tml47sYsd0gt0CgYBOZwgmakeF/stFKx8a1g+a/19jAHsLiAuwqonO
        vde7CUV6uQVz2QHbe0dqwmf96ZfoWR6re24URGvU96uSUkLwWMTBVqUB7Gy8Fio9
        xZDprMkzmIWoT3yQT//Cxc3jNc+YNkmd31vBL+lbuP4dbQci1JoXVvLM7FvNgCvt
        2nqZzQKBgERZQ2jUeBkmALfWg5Xp7nz7IFP4Nv6GFNp5rxwUv5uNzVmaF9QTYa0B
        5fQvl928mivAfrYb94LHIWitP+hUJrTFD7C3nUnSoR3vkVjrRkbrflp6u5XHPu9L
        lkObxz3LytLGCl9pTkmLi6LrLJxAyVu1YLP/mB8ciVkhFQa2z/0W
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAulqTZutBMcqi9r0NEPaY
        gRJ1TRqvqjlPc4+l+q1GKantO8ZcnSvVqnO5srUpd9eXYOFbH+KwMT3E1ZZPu2Se
        zJx2eKn1Gze8IWHF2K3/CwMppTL7JWeu3Ah6mg56Ls541M6OLPXQ5NAzl6deWNh/
        /Kpd5li/aqtJs7FqSzzWEPNW/AB235aehiNKlD+qIKmqls8QFljP8uwRoLXrSntP
        HUQBxNuRPLYCfPB6/jMWjHK+RyLvxTGnD9/zfeCwfhjKSW4jubZeLm3+NFts+aOx
        6FD+p7IvA6fi767RzisfkB4SYwGYfEwra0mukbSW2JQWUpFEoYMQ5+VCZQKqh4w7
        0QIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
