server:
  port: 4379
  keyphrase: secret
  keys:
  - id: sample
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEA3qY89Y1W4IJ0Zilq267O4O+sM3c8SVSv5sIImzOTJm/PA7tT
        fmJN52HBi+ve7ncrBkWRGq3SDyP9NYUfCu9ZQ/RdKq+5uqKBpyZsaA3bZpD9QHET
        RP0Pfc/S2aMNO6IyKpyQ7hQXgqIk+B7PLmpeFDlQRAmMlMAfQQ3AKSfljz4rlL6j
        rYJ9Oo4IlHyT03yKJGhPESoBtTqMoYuIZGjCOsSjkBwXoVYc4YhZcWocd+3Hv7wB
        +/pLji0vn02LWn0y8vFXgLUikRpF680SsSNPGgz7rcglkjw11lUDkcg8GgZrbyC/
        NUrds3l8BhwJpagNpoBVvFSvL2TTq6Kg7Fdt4QIDAQABAoIBAQDEFtbDUJq+GkbX
        nwyMtDVhp9Qac531248cBbG8tryXcot49ud+/Kct7Eugprjtfqi22lgEjifdy816
        8GY5pDkS/0l6ic9ijzLu+okpT2L2vyU8NxpIfTPCk2FY6iCCb8QNAV0nQSy/kXxL
        xh6j+2wmFaAae+qDK32bNrgRxyCHeQ4mXp0yLoLiBt7vHsYE5zClwVOoGbeuobsU
        vdTdn/fuE8qz6t8ADuaQNWmQ05hAYv9uganYLT3RUPhBJtiJiHYoQRkLi/jhTBA8
        0ITCmhwbbHoS6zU6CGZLZ/yzAaeUU1JPTMrO1v6eYWwNsd9+yypvl7HRTMqmOtHQ
        79pfdVUdAoGBAPJe7P39GU4qgy/qfAKDNBwwbhQHux9EgGJpAg6+hbekSiiPgiMf
        MNKrxicVDvuuKGmP7AofGRO2BQ/Aj4H598damjj/JqTmGAwXxNxW2FrhWEiOlnYr
        aG7DA7V7vHhxulE+ToPdEja3xpF9f7v0J4jPNeyoVphXiomZIjvpRflPAoGBAOsr
        aQ5su/WOjjBBqLnsqmOdWQB6+YTiqc8S33xkM3tJwPVEQAxCdt6kAIW1H3to8FVS
        pYsOpKru2Txtpq1o6IYKG8vDVzLjUbwcWbVDaEXB4dAr0xNWG5+RHBuYS5ghMK9d
        PFUGylhEwtdgjAeT1f/C7X5ygpbL6Anb/k+TK/nPAoGBAL9l6y1gNB2gQN0UBT5O
        slYYgLVcrY6xn9kXJ8LQ/fPZz55cRd7KgNm9QMwYOy7Rh6RlPXd4u2rvcOvRmwJ/
        jgZmLCgahj/uXMsf8hw2kMCj9/3EbFmBSgU+B63Huzw6Q3JpC8PiTsHbOvol6ztY
        QeguCl2LSmcfqo2i2oAJZXLNAoGAPBvBY3V5aV9BiqYNqVALkSCTsiK8ijGhM5Ng
        WhwGaJnGXypNsJSAa5HBrGtKG7IL09MnCu74OdSI5AAm3SX2YOROjHtmW1Rs/MbG
        SyVqjoHq5Nl+vu+Aaf2eEJORptW86uXK2PS+XWdd4c0EnZ800IWTTIGaTU7bBUIc
        s1wrnlMCgYBjHmpd37QLME13X5qmlGuMm1BgUvakxOk/f+n1A1Ht8CfoOllPTrzG
        BisoHQgwznojss5viZVcOso2nhwIIeU9cHVqHr13BjDvFiWkhjb+WJICRCjqxp9J
        Zd6V8QK8b0q39ljsyq8ulwDmuk+kcW0S1l3Md7XbkKvs5PMs0qehKQ==
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3qY89Y1W4IJ0Zilq267O
        4O+sM3c8SVSv5sIImzOTJm/PA7tTfmJN52HBi+ve7ncrBkWRGq3SDyP9NYUfCu9Z
        Q/RdKq+5uqKBpyZsaA3bZpD9QHETRP0Pfc/S2aMNO6IyKpyQ7hQXgqIk+B7PLmpe
        FDlQRAmMlMAfQQ3AKSfljz4rlL6jrYJ9Oo4IlHyT03yKJGhPESoBtTqMoYuIZGjC
        OsSjkBwXoVYc4YhZcWocd+3Hv7wB+/pLji0vn02LWn0y8vFXgLUikRpF680SsSNP
        Ggz7rcglkjw11lUDkcg8GgZrbyC/NUrds3l8BhwJpagNpoBVvFSvL2TTq6Kg7Fdt
        4QIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
