server:
  port: 4379
  keyphrase: a144a5ac-f0ac-4810-b810-7ed5360ac296
  keys:
  - id: signing-key
    algorithm: RS256
    use: sig
    data:
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpQIBAAKCAQEA0ad/9eXf9WIY20b4u0IMo9U41bYWXicvNDWvchFw9U6wphYV
        woRpWKBGqYAAiIbgY7ooccFQw88uE/Ht8SaSXwNtqmXbJGNITphRsmgzuyJpdYwt
        JgDiSZmwmS5WcccJD5QmNXxSK4tepP3fyphJdxxgj/yYoX8ZW6uytloz2Bm9AbrP
        Mo2EVSCiUvNtCWFPdHbV6fj7Y0YySO9fnqdjCNc+opbUrFts+ol7z1daNdCeQM9R
        DiD/HUHUsFkU/kN6nTSwpL6wejXnnW/Lnx68dG1BC/aH5bEQPht4kAk/CCJRymux
        JSbHN+y+yX8DoarefeRgz9ONgIJts9vb/GpM7wIDAQABAoIBAQC/tgL0wDeDEyjX
        mpZn5YXZamiGQ/NANWScwVqlW/2G02YE+bz8GkiamjUDWeEi9vLJPrktDDDmXNUt
        t9R052iBKYlmf61cIM1F0VMjaNWlEVqN+phuX/CMjNVHvW+eqvpGHJqz3fLljpQF
        G4FAqPDE0lYaVEjdpHNzuBW7WdB+kaKiYPW+zLEGmm6fPh/veVXqm1iHHAmyBOje
        PksonE+ZqhF2Syk5OxFQh/nFmvo3QpL2I1YbkpiyGSq86LxVRrPs7QnIwDnXrkG+
        ylkZZ2d7yd17OpaehLZtJIPL5hDl01gMMou+3AujS/hEoNQ6z+hr0hsAvC6MqsQG
        zSL5xi/BAoGBAPBA8RSjlFeEdW5h09bzhB1WbOgEAuc3fiWq5HfkMo3FGLnmvDzP
        umOnssIp+KugdZ9KBzuWxs4xdCNWJwso4fpQgHhQZYGm5RHQSIobIFktJGIJsM0S
        PQKBrONx2Wkw6lVlxgstyrR7Qovi05U9YZfVi2EE6/VLfSwW4VejfQOTAoGBAN9l
        JrdzHGAYwwjFxSFbKgflKtNnFipBhbRdoKazAjYflKQ9slaAcUiznXBrsovry8vE
        jXTreUWCGCNU/HKe3B0TdTVDY6nRvkob+d90EPmQRnk3RsgDNv9Fu15ELkboL2rP
        +kOkAmOYpZHv9dv5KooaEa6vS5d8XvYDSqXyBeK1AoGBAJdq1oYDcoKV4MzoqvJW
        F3XF+m1f2dSPjNmAku1czN+80JCZcxmAciBMmMT2XtsMDhWOOnC73iAl2uRKb+EA
        qytvgQhS4yaLYOOROaaQ4hpR8RQ4t00HqZvizmuqXTOGuKmJsv9opNCKvq4bDu6H
        +PIQi/9hcrTuFr2qzerGBwwxAoGBAKsUHrNMv0VEkVANjOr/ks+bC9H71zijFw7K
        yPYAjsf+JWomKYYfNSI1E3P9ti17dYXmT2Jj1mqJt4yPUAlDaVQHC7Kvmgp6Kt08
        UX5zt3A3shCwaU9RTvPtZhFJ65q3w2BsR783QfEd/GYnu0QrrA0466O4cQ5g26RR
        XwB4uVMlAoGABrtoCN/JPz9OCxJsXRwEbYK3t3yEPeO6W7hMm9NvdvhAJfH76I6N
        6RG4ZrG+FzdHkocZnUTy6c5OZ07isyvXm3HCM5B0K85OvQ+p/Jz0IaJbfGhO6XUW
        kQoYUA4yU2Rh/Y6GZ+gOQWw3k5VNyGCb5snPW7Ee4mjl3j/UgzxQ8o4=
        -----END RSA PRIVATE KEY-----
      public: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0ad/9eXf9WIY20b4u0IM
        o9U41bYWXicvNDWvchFw9U6wphYVwoRpWKBGqYAAiIbgY7ooccFQw88uE/Ht8SaS
        XwNtqmXbJGNITphRsmgzuyJpdYwtJgDiSZmwmS5WcccJD5QmNXxSK4tepP3fyphJ
        dxxgj/yYoX8ZW6uytloz2Bm9AbrPMo2EVSCiUvNtCWFPdHbV6fj7Y0YySO9fnqdj
        CNc+opbUrFts+ol7z1daNdCeQM9RDiD/HUHUsFkU/kN6nTSwpL6wejXnnW/Lnx68
        dG1BC/aH5bEQPht4kAk/CCJRymuxJSbHN+y+yX8DoarefeRgz9ONgIJts9vb/GpM
        7wIDAQAB
        -----END RSA PUBLIC KEY-----
clients: []
