// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

import (
	"database/sql"
)

type AuthRequest struct {
	ID                  string
	ApplicationID       string
	RedirectUri         string
	State               string
	Prompt              string
	LoginHint           string
	MaxAuthAgeSeconds   int64
	UserID              string
	Scopes              string
	ResponseType        string
	ResponseMode        string
	Nonce               string
	CodeChallenge       string
	CodeChallengeMethod string
	Complete            bool
	CreatedAt           int64
	AuthenticatedAt     int64
	AuthCode            sql.NullString
}

type Key struct {
	ID         string
	Alg        string
	Usage      string
	PublicKey  string
	PrivateKey string
	CreatedAt  int64
}

type RefreshToken struct {
	ID            string
	AuthTime      int64
	Amr           sql.NullString
	Audience      string
	Subject       string
	ApplicationID string
	Expiration    int64
	Scopes        string
	CreatedAt     int64
}

type Token struct {
	ID             string
	AuthRequestID  sql.NullString
	ApplicationID  string
	RefreshTokenID sql.NullString
	Subject        string
	Audience       string
	Expiration     int64
	Scopes         string
	CreatedAt      int64
}
