// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

type AuthRequest struct {
	ID                  string
	ApplicationID       string
	RedirectUri         string
	State               string
	Prompt              string
	LoginHint           string
	MaxAuthAgeSeconds   int64
	UserID              string
	Scopes              string
	ResponseType        string
	ResponseMode        string
	Nonce               string
	CodeChallenge       string
	CodeChallengeMethod string
	Complete            bool
	CreatedAt           int64
	AuthenticatedAt     int64
}
